language: ruby
rvm:
  - 1.8.7
env:
  - DB=mysql
  - DB=postgresql
  - DB=sqlite3
before_install:
  - "ci/setup" 
  - "gem update --system 1.3.7"
  # - "rvm @global do gem uninstall -ax rubygems-bundler"
  - "gem install rake  -v=0.9.6  --no-ri --no-rdoc"
  - "gem install pg    -v=0.17.1 --no-ri --no-rdoc"
  - "gem install mysql sqlite3   --no-ri --no-rdoc"
  - "gem install rails -v=2.3.2  --no-ri --no-rdoc"
  - "rake _0.9.6_ gems:install --trace"
  - "rake _0.9.6_ db:migrate"
script: "rake _0.9.6_ test"