language: ruby
bundler_args: "--full-index --without development"
# cache: bundler
sudo: required
rvm:
- 2.3.4
before_install: test/ci/before_install
before_script: test/ci/before_script
script: xvfb-run bundle exec rake test:models test:libs test:controllers DRIVER=webkit
services:
- redis-server
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=COVERALLS_REPO_TOKEN
  email: false
  slack:
    secure: v1/ya/fyroy3BmW9FDMmKi3lwamnzY6ktQAU/vEJCg4AgvauY0QJthMsLXOBb3RnhFWao2Kj2H40XjI7VtH3z46VEq6DPLURBqmAc24c30ZMi/XIM9YqauYeEPHPhM0nDQY+s0ovU2uX/1w7uv/atNjy0n643An61Em+qPwIW5U=
