# Codes come from ISO4217
# This file defines all used currencies defined by the ISO
# All these data must not contain l10n or i18n data.
# Units used in currencies are the most international as possible
# The units can be overriden with locales (config/locales).
# Last check: 2012-03-09
AED:
  active: true
  countries: [ae]
  number: '784'
  precision: 2
  iso_name: UAE Dirham
AFN:
  active: true
  countries: [af]
  number: '971'
  precision: 2
  iso_name: Afghani
ALL:
  active: true
  countries: [al]
  number: '008'
  precision: 2
  iso_name: Lek
AMD:
  active: true
  countries: [am]
  number: '051'
  precision: 2
  iso_name: Armenian Dram
ANG:
  active: true
  countries: [nl]
  number: '532'
  precision: 2
  iso_name: Netherlands Antillean Guilder
AOA:
  active: true
  countries: [ao]
  number: '973'
  precision: 2
  iso_name: Kwanza
ARS:
  active: true
  countries: [ar]
  number: '032'
  precision: 2
  iso_name: Argentine Peso
AUD:
  active: true
  countries: [au, cc, cx, hm, ki, nf, nr, tv]
  number: '036'
  precision: 2
  iso_name: Australian Dollar
AWG:
  active: true
  countries: [aw]
  number: '533'
  precision: 2
  iso_name: Aruban Florin
AZN:
  active: true
  countries: [az]
  number: '944'
  precision: 2
  iso_name: Azerbaijanian Manat
BAM:
  active: true
  countries: [ba]
  number: '977'
  precision: 2
  iso_name: Convertible Mark
BBD:
  active: true
  countries: [bb]
  number: '052'
  precision: 2
  iso_name: Barbados Dollar
BDT:
  active: true
  countries: [bd]
  number: '050'
  precision: 2
  iso_name: Taka
BGN:
  active: true
  countries: [bg]
  number: '975'
  precision: 2
  iso_name: Bulgarian Lev
BHD:
  active: true
  countries: [bh]
  number: '048'
  precision: 3
  iso_name: Bahraini Dinar
BIF:
  active: true
  countries: [bi]
  number: '108'
  precision: 0
  iso_name: Burundi Franc
BMD:
  active: true
  countries: [bm]
  number: '060'
  precision: 2
  iso_name: Bermudian Dollar
BND:
  active: true
  countries: [bn]
  number: '096'
  precision: 2
  iso_name: Brunei Dollar
BOB:
  active: true
  countries: [bo]
  number: '068'
  precision: 2
  iso_name: Boliviano
BOV:
  active: true
  countries: [bo]
  number: '984'
  precision: 2
  iso_name: Mvdol
BRL:
  active: true
  countries: [br]
  number: '986'
  precision: 2
  iso_name: Brazilian Real
BSD:
  active: true
  countries: [bs]
  number: '044'
  precision: 2
  iso_name: Bahamian Dollar
BTN:
  active: true
  countries: [bt]
  number: '064'
  precision: 2
  iso_name: Ngultrum
BWP:
  active: true
  countries: [bw]
  number: '072'
  precision: 2
  iso_name: Pula
BYR:
  active: true
  countries: [by]
  number: '974'
  precision: 0
  iso_name: Belarussian Ruble
BZD:
  active: true
  countries: [bz]
  number: '084'
  precision: 2
  iso_name: Belize Dollar
CAD:
  active: true
  countries: [ca]
  number: '124'
  precision: 2
  iso_name: Canadian Dollar
CDF:
  active: true
  countries: [cd]
  number: '976'
  precision: 2
  iso_name: Congolese Franc
CHE:
  active: true
  countries: [ch]
  number: '947'
  precision: 2
  iso_name: WIR Euro
CHF:
  active: true
  countries: [ch, li]
  number: '756'
  precision: 2
  iso_name: Swiss Franc
CHW:
  active: true
  countries: [ch]
  number: '948'
  precision: 2
  iso_name: WIR Franc
CLF:
  active: true
  countries: [cl]
  number: '990'
  precision: 0
  iso_name: Unidades de fomento
CLP:
  active: true
  countries: [cl]
  number: '152'
  precision: 0
  iso_name: Chilean Peso
CNY:
  active: true
  countries: [cn]
  number: '156'
  precision: 2
  iso_name: Yuan Renminbi
COP:
  active: true
  countries: [co]
  number: '170'
  precision: 2
  iso_name: Colombian Peso
COU:
  active: true
  countries: [co]
  number: '970'
  precision: 2
  iso_name: Unidad de Valor Real
CRC:
  active: true
  countries: [cr]
  number: '188'
  precision: 2
  iso_name: Costa Rican Colon
CUC:
  active: true
  countries: [cu]
  number: '931'
  precision: 2
  iso_name: Peso Convertible
CUP:
  active: true
  countries: [cu]
  number: '192'
  precision: 2
  iso_name: Cuban Peso
CVE:
  active: true
  countries: [cv]
  number: '132'
  precision: 2
  iso_name: Cape Verde Escudo
CZK:
  active: true
  countries: [cz]
  number: '203'
  precision: 2
  iso_name: Czech Koruna
DJF:
  active: true
  countries: [dj]
  number: '262'
  precision: 0
  iso_name: Djibouti Franc
DKK:
  active: true
  countries: [dk, fo, gl]
  number: '208'
  precision: 2
  iso_name: Danish Krone
DOP:
  active: true
  countries: [do]
  number: '214'
  precision: 2
  iso_name: Dominican Peso
DZD:
  active: true
  countries: [dz]
  number: '012'
  precision: 2
  iso_name: Algerian Dinar
EGP:
  active: true
  countries: [eg]
  number: '818'
  precision: 2
  iso_name: Egyptian Pound
ERN:
  active: true
  countries: [er]
  number: '232'
  precision: 2
  iso_name: Nakfa
ETB:
  active: true
  countries: [et]
  number: '230'
  precision: 2
  iso_name: Ethiopian Birr
EUR:
  active: true
  cash: [0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1, 2, 5, 10, 20, 50, 100, 200, 500]
  countries: [ad, at, ax, be, bl, cy, de, ee, es, fi, fr, gf, gp, gr, ie, it, lu, mc, me, mf, mq, mt, nl, pm, pt, si, sk, sm, tf, va, yt]
  number: '978'
  precision: 2
  iso_name: Euro
  unit: '€'
FJD:
  active: true
  countries: [fj]
  number: '242'
  precision: 2
  iso_name: Fiji Dollar
FKP:
  active: true
  countries: [fk]
  number: '238'
  precision: 2
  iso_name: Falkland Islands Pound
FRF:
  active: false
  cash: [0.05, 0.1, 0.2, 0.5, 1, 2, 5, 10, 20, 50, 100, 200, 500]
  countries: [fr]
  number: "250"
  precision: 2
GBP:
  active: true
  countries: [gb, gg, im, je]
  number: '826'
  precision: 2
  iso_name: Pound Sterling
GEL:
  active: true
  countries: [ge]
  number: '981'
  precision: 2
  iso_name: Lari
GHS:
  active: true
  countries: [gh]
  number: '936'
  precision: 2
  iso_name: Ghana Cedi
GIP:
  active: true
  countries: [gi]
  number: '292'
  precision: 2
  iso_name: Gibraltar Pound
GMD:
  active: true
  countries: [gm]
  number: '270'
  precision: 2
  iso_name: Dalasi
GNF:
  active: true
  countries: [gn]
  number: '324'
  precision: 0
  iso_name: Guinea Franc
GTQ:
  active: true
  countries: [gt]
  number: '320'
  precision: 2
  iso_name: Quetzal
GYD:
  active: true
  countries: [gy]
  number: '328'
  precision: 2
  iso_name: Guyana Dollar
HKD:
  active: true
  countries: [hk]
  number: '344'
  precision: 2
  iso_name: Hong Kong Dollar
HNL:
  active: true
  countries: [hn]
  number: '340'
  precision: 2
  iso_name: Lempira
HRK:
  active: true
  countries: [hr]
  number: '191'
  precision: 2
  iso_name: Croatian Kuna
HTG:
  active: true
  countries: [ht]
  number: '332'
  precision: 2
  iso_name: Gourde
HUF:
  active: true
  countries: [hu]
  number: '348'
  precision: 2
  iso_name: Forint
IDR:
  active: true
  countries: [id]
  number: '360'
  precision: 2
  iso_name: Rupiah
ILS:
  active: true
  countries: [il]
  number: '376'
  precision: 2
  iso_name: New Israeli Sheqel
INR:
  active: true
  countries: [bt, in]
  number: '356'
  precision: 2
  iso_name: Indian Rupee
IQD:
  active: true
  countries: [iq]
  number: '368'
  precision: 3
  iso_name: Iraqi Dinar
IRR:
  active: true
  countries: [ir]
  number: '364'
  precision: 2
  iso_name: Iranian Rial
ISK:
  active: true
  countries: [is]
  number: '352'
  precision: 0
  iso_name: Iceland Krona
JMD:
  active: true
  countries: [jm]
  number: '388'
  precision: 2
  iso_name: Jamaican Dollar
JOD:
  active: true
  countries: [jo]
  number: '400'
  precision: 3
  iso_name: Jordanian Dinar
JPY:
  active: true
  cash: [1, 5, 10, 50, 100, 500, 1000, 2000, 5000, 10000]
  countries: [jp]
  number: '392'
  precision: 0
  iso_name: Yen
  unit: '¥'
KES:
  active: true
  countries: [ke]
  number: '404'
  precision: 2
  iso_name: Kenyan Shilling
KGS:
  active: true
  countries: [kg]
  number: '417'
  precision: 2
  iso_name: Som
KHR:
  active: true
  countries: [kh]
  number: '116'
  precision: 2
  iso_name: Riel
KMF:
  active: true
  countries: [km]
  number: '174'
  precision: 0
  iso_name: Comoro Franc
KPW:
  active: true
  countries: [kp]
  number: '408'
  precision: 2
  iso_name: North Korean Won
KRW:
  active: true
  countries: [kr]
  number: '410'
  precision: 0
  iso_name: Won
KWD:
  active: true
  countries: [kw]
  number: '414'
  precision: 3
  iso_name: Kuwaiti Dinar
KYD:
  active: true
  countries: [ky]
  number: '136'
  precision: 2
  iso_name: Cayman Islands Dollar
KZT:
  active: true
  countries: [kz]
  number: '398'
  precision: 2
  iso_name: Tenge
LAK:
  active: true
  countries: [la]
  number: '418'
  precision: 2
  iso_name: Kip
LBP:
  active: true
  countries: [lb]
  number: '422'
  precision: 2
  iso_name: Lebanese Pound
LKR:
  active: true
  countries: [lk]
  number: '144'
  precision: 2
  iso_name: Sri Lanka Rupee
LRD:
  active: true
  countries: [lr]
  number: '430'
  precision: 2
  iso_name: Liberian Dollar
LSL:
  active: true
  countries: [ls]
  number: '426'
  precision: 2
  iso_name: Loti
LTL:
  active: true
  countries: [lt]
  number: '440'
  precision: 2
  iso_name: Lithuanian Litas
LVL:
  active: true
  countries: [lv]
  number: '428'
  precision: 2
  iso_name: Latvian Lats
LYD:
  active: true
  countries: [LIBYA]
  number: '434'
  precision: 3
  iso_name: Libyan Dinar
MAD:
  active: true
  countries: [eh, ma]
  number: '504'
  precision: 2
  iso_name: Moroccan Dirham
MDL:
  active: true
  countries: [md]
  number: '498'
  precision: 2
  iso_name: Moldovan Leu
MGA:
  active: true
  countries: [mg]
  number: '969'
  precision: 2
  iso_name: Malagasy Ariary
MKD:
  active: true
  countries: [mk]
  number: '807'
  precision: 2
  iso_name: Denar
MMK:
  active: true
  countries: [mm]
  number: '104'
  precision: 2
  iso_name: Kyat
MNT:
  active: true
  countries: [mn]
  number: '496'
  precision: 2
  iso_name: Tugrik
MOP:
  active: true
  countries: [mo]
  number: '446'
  precision: 2
  iso_name: Pataca
MRO:
  active: true
  countries: [mr]
  number: '478'
  precision: 2
  iso_name: Ouguiya
MUR:
  active: true
  countries: [mu]
  number: '480'
  precision: 2
  iso_name: Mauritius Rupee
MVR:
  active: true
  countries: [mv]
  number: '462'
  precision: 2
  iso_name: Rufiyaa
MWK:
  active: true
  countries: [mw]
  number: '454'
  precision: 2
  iso_name: Kwacha
MXN:
  active: true
  countries: [mx]
  number: '484'
  precision: 2
  iso_name: Mexican Peso
MXV:
  active: true
  countries: [mx]
  number: '979'
  precision: 2
  iso_name: Mexican Unidad de Inversion (UDI)
MYR:
  active: true
  countries: [my]
  number: '458'
  precision: 2
  iso_name: Malaysian Ringgit
MZN:
  active: true
  countries: [mz]
  number: '943'
  precision: 2
  iso_name: Mozambique Metical
NAD:
  active: true
  countries: [na]
  number: '516'
  precision: 2
  iso_name: Namibia Dollar
NGN:
  active: true
  countries: [ng]
  number: '566'
  precision: 2
  iso_name: Naira
NIO:
  active: true
  countries: [ni]
  number: '558'
  precision: 2
  iso_name: Cordoba Oro
NOK:
  active: true
  countries: [no, bv, sj]
  number: '578'
  precision: 2
  iso_name: Norwegian Krone
NPR:
  active: true
  countries: [np]
  number: '524'
  precision: 2
  iso_name: Nepalese Rupee
NZD:
  active: true
  countries: [ck, nu, nz, pn, tk]
  number: '554'
  precision: 2
  iso_name: New Zealand Dollar
OMR:
  active: true
  countries: [om]
  number: '512'
  precision: 3
  iso_name: Rial Omani
PAB:
  active: true
  countries: [pa]
  number: '590'
  precision: 2
  iso_name: Balboa
PEN:
  active: true
  countries: [pe]
  number: '604'
  precision: 2
  iso_name: Nuevo Sol
PGK:
  active: true
  countries: [pg]
  number: '598'
  precision: 2
  iso_name: Kina
PHP:
  active: true
  countries: [ph]
  number: '608'
  precision: 2
  iso_name: Philippine Peso
PKR:
  active: true
  countries: [pk]
  number: '586'
  precision: 2
  iso_name: Pakistan Rupee
PLN:
  active: true
  countries: [pl]
  number: '985'
  precision: 2
  iso_name: Zloty
PYG:
  active: true
  countries: [py]
  number: '600'
  precision: 0
  iso_name: Guarani
QAR:
  active: true
  countries: [qa]
  number: '634'
  precision: 2
  iso_name: Qatari Rial
RON:
  active: true
  countries: [ro]
  number: '946'
  precision: 2
  iso_name: New Romanian Leu
RSD:
  active: true
  countries: [rs]
  number: '941'
  precision: 2
  iso_name: Serbian Dinar
RUB:
  active: true
  countries: [ru]
  number: '643'
  precision: 2
  iso_name: Russian Ruble
RWF:
  active: true
  countries: [rw]
  number: '646'
  precision: 0
  iso_name: Rwanda Franc
SAR:
  active: true
  countries: [sa]
  number: '682'
  precision: 2
  iso_name: Saudi Riyal
SBD:
  active: true
  countries: [sb]
  number: '090'
  precision: 2
  iso_name: Solomon Islands Dollar
SCR:
  active: true
  countries: [sc]
  number: '690'
  precision: 2
  iso_name: Seychelles Rupee
SDG:
  active: true
  countries: [sd]
  number: '938'
  precision: 2
  iso_name: Sudanese Pound
SEK:
  active: true
  countries: [se]
  number: '752'
  precision: 2
  iso_name: Swedish Krona
SGD:
  active: true
  countries: [sg]
  number: '702'
  precision: 2
  iso_name: Singapore Dollar
SHP:
  active: true
  countries: [sh]
  number: '654'
  precision: 2
  iso_name: Saint Helena Pound
SLL:
  active: true
  countries: [sl]
  number: '694'
  precision: 2
  iso_name: Leone
SOS:
  active: true
  countries: [so]
  number: '706'
  precision: 2
  iso_name: Somali Shilling
SRD:
  active: true
  countries: [sr]
  number: '968'
  precision: 2
  iso_name: Surinam Dollar
SSP:
  active: true
  countries: [ss]
  number: '728'
  precision: 2
  iso_name: South Sudanese Pound
STD:
  active: true
  countries: [st]
  number: '678'
  precision: 2
  iso_name: Dobra
SVC:
  active: true
  countries: [sv]
  number: '222'
  precision: 2
  iso_name: El Salvador Colon
SYP:
  active: true
  countries: [sy]
  number: '760'
  precision: 2
  iso_name: Syrian Pound
SZL:
  active: true
  countries: [sz]
  number: '748'
  precision: 2
  iso_name: Lilangeni
THB:
  active: true
  countries: [th]
  number: '764'
  precision: 2
  iso_name: Baht
TJS:
  active: true
  countries: [tj]
  number: '972'
  precision: 2
  iso_name: Somoni
TMT:
  active: true
  countries: [tm]
  number: '934'
  precision: 2
  iso_name: Turkmenistan New Manat
TND:
  active: true
  countries: [tn]
  number: '788'
  precision: 3
  iso_name: Tunisian Dinar
TOP:
  active: true
  countries: [to]
  number: '776'
  precision: 2
  iso_name: Pa’anga
TRY:
  active: true
  countries: [tr]
  number: '949'
  precision: 2
  iso_name: Turkish Lira
TTD:
  active: true
  countries: [tt]
  number: '780'
  precision: 2
  iso_name: Trinidad and Tobago Dollar
TWD:
  active: true
  countries: [tw]
  number: '901'
  precision: 2
  iso_name: New Taiwan Dollar
TZS:
  active: true
  countries: [tz]
  number: '834'
  precision: 2
  iso_name: Tanzanian Shilling
UAH:
  active: true
  countries: [ua]
  number: '980'
  precision: 2
  iso_name: Hryvnia
UGX:
  active: true
  countries: [ug]
  number: '800'
  precision: 2
  iso_name: Uganda Shilling
USD:
  active: true
  cash: [0.01, 0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10, 20, 50, 100]
  countries: [as, ec, fm, gu, ht, io, mh, mp, nl, pa, pr, pw, sv, tc, tl, um, us, vg, vi]
  number: '840'
  precision: 2
  iso_name: US Dollar
  unit: '$'
USN:
  active: true
  countries: [us]
  number: '997'
  precision: 2
  iso_name: US Dollar (Next day)
USS:
  active: true
  countries: [us]
  number: '998'
  precision: 2
  iso_name: US Dollar (Same day)
UYI:
  active: true
  countries: [uy]
  number: '940'
  precision: 0
  iso_name: Uruguay Peso en Unidades Indexadas (URUIURUI)
UYU:
  active: true
  countries: [uy]
  number: '858'
  precision: 2
  iso_name: Peso Uruguayo
UZS:
  active: true
  countries: [uz]
  number: '860'
  precision: 2
  iso_name: Uzbekistan Sum
VEF:
  active: true
  countries: [ve]
  number: '937'
  precision: 2
  iso_name: Bolivar Fuerte
VND:
  active: true
  countries: [vn]
  number: '704'
  precision: 0
  iso_name: Dong
VUV:
  active: true
  countries: [vu]
  number: '548'
  precision: 0
  iso_name: Vatu
WST:
  active: true
  countries: [ws]
  number: '882'
  precision: 2
  iso_name: Tala
YER:
  active: true
  countries: [ye]
  number: '886'
  precision: 2
  iso_name: Yemeni Rial
ZAR:
  active: true
  countries: [ls, na, za]
  number: '710'
  precision: 2
  iso_name: Rand
ZMK:
  active: true
  countries: [zm]
  number: '894'
  precision: 2
  iso_name: Zambian Kwacha
ZWL:
  active: true
  countries: [zw]
  number: '932'
  precision: 2
  iso_name: Zimbabwe Dollar