open_street_map:
  options:
    attribution: '&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>'
  variants:
    mapnik:
      url: 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
      enabled: yes
    black_and_white:
      url: 'http://{s}.www.toolserver.org/tiles/bw-mapnik/{z}/{x}/{y}.png'
    de:
      url: 'http://{s}.tile.openstreetmap.de/tiles/osmde/{z}/{x}/{y}.png'
    hot:
      url: 'http://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png'
      enabled: yes
      by_default: yes
      options:
        attribution: '{attribution.OpenStreetMap}, Tiles courtesy of <a href="http://hot.openstreetmap.org/" target="_blank">Humanitarian OpenStreetMap Team</a>'

thunderforest:
  options:
    attribution: 'Maps © <a href="http://www.thunderforest.com">Thunderforest</a>, Data © <a href="http://www.openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    subdomains: 'abc'
  variants:
    outdoors:
      url: 'https://{s}.tile.thunderforest.com/outdoors/{z}/{x}/{y}.png'
    cycle:
      url: 'https://{s}.tile.thunderforest.com/cycle/{z}/{x}/{y}.png'
    transport:
      url: 'https://{s}.tile.thunderforest.com/transport/{z}/{x}/{y}.png'
    transport_dark:
      url: 'https://{s}.tile.thunderforest.com/transport-dark/{z}/{x}/{y}.png'
    landscape:
      enabled: yes
      url: 'https://{s}.tile.thunderforest.com/landscape/{z}/{x}/{y}.png'

open_sea_map:
  url: 'http://tiles.openseamap.org/seamark/{z}/{x}/{y}.png'
  options:
    attribution: 'Map data: &copy; <a href="http://www.openseamap.org">OpenSeaMap</a> contributors'

open_map_surfer:
  url: 'http://korona.geog.uni-heidelberg.de/tiles/roads/x={x}&y={y}&z={z}'
  options:
    attribution: 'Imagery from <a href="http://giscience.uni-hd.de/">GIScience Research Group @ University of Heidelberg</a> &mdash; Map data {attribution.OpenStreetMap}'
  variants:
    roads:
    admin_bounds:
      url: 'http://korona.geog.uni-heidelberg.de/tiles/adminb/x={x}&y={y}&z={z}'
    grayscale:
      url: 'http://korona.geog.uni-heidelberg.de/tiles/roadsg/x={x}&y={y}&z={z}'

map_quest_open:
  url: 'http://otile{s}.mqcdn.com/tiles/1.0.0/map/{z}/{x}/{y}.jpg'
  options:
    attribution: 'Tiles Courtesy of <a href="http://www.mapquest.com/">MapQuest</a> &mdash; Map data {attribution.OpenStreetMap}'
    subdomains: '1234'

  variants:
    default:
    aerial:
      url: 'http://oatile{s}.mqcdn.com/tiles/1.0.0/sat/{z}/{x}/{y}.jpg'
      options:
        attribution: 'Tiles Courtesy of <a href="http://www.mapquest.com/">MapQuest</a> &mdash; Portions Courtesy NASA/JPL-Caltech and U.S. Depart. of Agriculture, Farm Service Agency'

stamen:
  options:
    attribution: 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data {attribution.OpenStreetMap}'
    subdomains: 'abcd'
    min_zoom: 0
    max_zoom: 20
  variants:
    toner:
     url: 'http://{s}.tile.stamen.com/toner/{z}/{x}/{y}.png'
    toner_background:
      url: 'http://{s}.tile.stamen.com/toner-background/{z}/{x}/{y}.png'
    toner_hybrid:
      url: 'http://{s}.tile.stamen.com/toner-hybrid/{z}/{x}/{y}.png'
    toner_lines:
      url: 'http://{s}.tile.stamen.com/toner-lines/{z}/{x}/{y}.png'
    toner_labels:
      url: 'http://{s}.tile.stamen.com/toner-labels/{z}/{x}/{y}.png'
    toner_lite:
      url: 'http://{s}.tile.stamen.com/toner-lite/{z}/{x}/{y}.png'
    terrain:
      url: 'http://{s}.tile.stamen.com/terrain/{z}/{x}/{y}.jpg'
      options:
        min_zoom: 4
        max_zoom: 18
    terrain_background:
      url: 'http://{s}.tile.stamen.com/terrain-background/{z}/{x}/{y}.jpg'
      options:
        min_zoom: 4
        max_zoom: 18
    watercolor:
      url: 'http://{s}.tile.stamen.com/watercolor/{z}/{x}/{y}.jpg'
      options:
        min_zoom: 3
        max_zoom: 16

esri:
  url: 'http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}'
  options:
    attribution: 'Tiles &copy; Esri'

  variants:
    world_street_map:
      options:
        attribution: '{attribution.Esri} &mdash; Source: Esri, DeLorme, NAVTEQ, USGS, Intermap, iPC, NRCAN, Esri Japan, METI, Esri China (Hong Kong), Esri (Thailand), TomTom, 2012'
    de_lorme:
      url: 'http://server.arcgisonline.com/ArcGIS/rest/services/Specialty/DeLorme_World_Base_Map/MapServer/tile/{z}/{y}/{x}'
      options:
        min_zoom: 1
        max_zoom: 11
        attribution: '{attribution.Esri} &mdash; Copyright: &copy;2012 DeLorme'
    world_topo_map:
      url: 'http://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}'
      options:
        attribution:
          '{attribution.Esri} &mdash; Esri, DeLorme, NAVTEQ, TomTom, Intermap, iPC, USGS, FAO, NPS, NRCAN, GeoBase, Kadaster NL, Ordnance Survey, Esri Japan, METI, Esri China (Hong Kong), and the GIS User Community'
    world_imagery:
      url: 'http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'
      enabled: yes
      options:
        attribution:
          '{attribution.Esri} &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community'
    world_terrain:
      url: 'http://server.arcgisonline.com/ArcGIS/rest/services/World_Terrain_Base/MapServer/tile/{z}/{y}/{x}'
      options:
        max_zoom: 13
        attribution:
          '{attribution.Esri} &mdash; Source: USGS, Esri, TANA, DeLorme, and NPS'
    world_shaded_relief:
      url: 'http://server.arcgisonline.com/ArcGIS/rest/services/World_Shaded_Relief/MapServer/tile/{z}/{y}/{x}'
      options:
        max_zoom: 13
        attribution: '{attribution.Esri} &mdash; Source: Esri'
    world_physical:
      url: 'http://server.arcgisonline.com/ArcGIS/rest/services/World_Physical_Map/MapServer/tile/{z}/{y}/{x}'
      options:
        max_zoom: 8
        attribution: '{attribution.Esri} &mdash; Source: US National Park Service'
    ocean_base_map:
      url: 'http://services.arcgisonline.com/ArcGIS/rest/services/Ocean_Basemap/MapServer/tile/{z}/{y}/{x}'
      options:
        max_zoom: 13
        attribution: '{attribution.Esri} &mdash; Sources: GEBCO, NOAA, CHS, OSU, UNH, CSUMB, National Geographic, DeLorme, NAVTEQ, and Esri'
    nat_geo_world_map:
      url: 'http://services.arcgisonline.com/ArcGIS/rest/services/NatGeo_World_Map/MapServer/tile/{z}/{y}/{x}'
      options:
        max_zoom: 16
        attribution: '{attribution.Esri} &mdash; National Geographic, Esri, DeLorme, NAVTEQ, UNEP-WCMC, USGS, NASA, ESA, METI, NRCAN, GEBCO, NOAA, iPC'
    world_gray_canvas:
      url: 'http://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}'
      options:
        max_zoom: 16
        attribution: '{attribution.Esri} &mdash; Esri, DeLorme, NAVTEQ'

acetate:
  url: 'http://a{s}.acetate.geoiq.com/tiles/acetate-hillshading/{z}/{x}/{y}.png'
  options:
    attribution: '&copy;2012 Esri & Stamen, Data from OSM and Natural Earth'
    subdomains: '0123'
    min_zoom: 2
    max_zoom: 18

  variants:
    all:
    basemap:
      url: 'http://a{s}.acetate.geoiq.com/tiles/acetate-base/{z}/{x}/{y}.png'
    terrain:
      url: 'http://a{s}.acetate.geoiq.com/tiles/terrain/{z}/{x}/{y}.png'
    foreground:
      url: 'http://a{s}.acetate.geoiq.com/tiles/acetate-fg/{z}/{x}/{y}.png'
    roads:
      url: 'http://a{s}.acetate.geoiq.com/tiles/acetate-roads/{z}/{x}/{y}.png'
    labels:
      url: 'http://a{s}.acetate.geoiq.com/tiles/acetate-labels/{z}/{x}/{y}.png'
    hillshading:
      url: 'http://a{s}.acetate.geoiq.com/tiles/hillshading/{z}/{x}/{y}.png'
