open_street_map:
  type: map_background
  options:
    attribution: '&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>'
  variants:
    mapnik:
      url: 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
      enabled: yes
      options:
        max_zoom: 19
    black_and_white:
      url: 'http://{s}.www.toolserver.org/tiles/bw-mapnik/{z}/{x}/{y}.png'
      options:
        max_zoom: 18
    de:
      url: 'http://{s}.tile.openstreetmap.de/tiles/osmde/{z}/{x}/{y}.png'
      options:
        max_zoom: 18
    france:
      url: 'http://{s}.tile.openstreetmap.de/tiles/osmde/{z}/{x}/{y}.png'
      options:
        max_zoom: 19
    hot:
      url: 'http://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png'
      enabled: yes
      by_default: yes
      options:
        max_zoom: 19
        attribution: '&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Tiles courtesy of <a href="http://hot.openstreetmap.org/" target="_blank">Humanitarian OpenStreetMap Team</a>'

thunderforest:
  type: map_background
  options:
    attribution: 'Maps © <a href="http://www.thunderforest.com">Thunderforest</a>, Data © <a href="http://www.openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    subdomains: 'abc'
  variants:
    outdoors:
      url: 'https://{s}.tile.thunderforest.com/outdoors/{z}/{x}/{y}.png'
    cycle:
      url: 'https://{s}.tile.thunderforest.com/cycle/{z}/{x}/{y}.png'
    transport:
      url: 'https://{s}.tile.thunderforest.com/transport/{z}/{x}/{y}.png'
      options:
        max_zoom: 19
    transport_dark:
      url: 'https://{s}.tile.thunderforest.com/transport-dark/{z}/{x}/{y}.png'
      options:
        max_zoom: 19
    landscape:
      enabled: yes
      url: 'https://{s}.tile.thunderforest.com/landscape/{z}/{x}/{y}.png'

open_map_surfer:
  type: map_background
  url: 'http://korona.geog.uni-heidelberg.de/tiles/roads/x={x}&y={y}&z={z}'
  options:
    attribution: 'Imagery from <a href="http://giscience.uni-hd.de/">GIScience Research Group @ University of Heidelberg</a> &mdash; Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>'
    max_zoom: 19
  variants:
    roads:
    grayscale:
      url: 'http://korona.geog.uni-heidelberg.de/tiles/roadsg/x={x}&y={y}&z={z}'

stamen:
  type: map_background
  options:
    attribution: 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>'
    subdomains: 'abcd'
    min_zoom: 0
    max_zoom: 17
  variants:
    toner:
      url: 'http://{s}.tile.stamen.com/toner/{z}/{x}/{y}.png'
    toner_background:
      url: 'http://{s}.tile.stamen.com/toner-background/{z}/{x}/{y}.png'
    toner_lite:
      url: 'http://{s}.tile.stamen.com/toner-lite/{z}/{x}/{y}.png'
    watercolor:
      url: 'http://{s}.tile.stamen.com/watercolor/{z}/{x}/{y}.jpg'
      options:
        min_zoom: 3
        max_zoom: 15

esri:
  type: map_background
  url: 'http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}'
  options:
    attribution: 'Tiles &copy; Esri'
  variants:
    world_street_map:
      options:
        max_zoom: 19
        attribution: 'Tiles &copy; Esri &mdash; Source: Esri, DeLorme, NAVTEQ, USGS, Intermap, iPC, NRCAN, Esri Japan, METI, Esri China (Hong Kong), Esri (Thailand), TomTom, 2012'
    de_lorme:
      url: 'http://server.arcgisonline.com/ArcGIS/rest/services/Specialty/DeLorme_World_Base_Map/MapServer/tile/{z}/{y}/{x}'
      options:
        min_zoom: 1
        max_zoom: 11
        attribution: 'Tiles &copy; Esri &mdash; Copyright: &copy;2012 DeLorme'
    world_topo_map:
      url: 'http://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}'
      options:
        max_zoom: 19
        attribution:
          'Tiles &copy; Esri &mdash; Esri, DeLorme, NAVTEQ, TomTom, Intermap, iPC, USGS, FAO, NPS, NRCAN, GeoBase, Kadaster NL, Ordnance Survey, Esri Japan, METI, Esri China (Hong Kong), and the GIS User Community'
    world_imagery:
      url: 'http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'
      enabled: yes
      options:
        max_zoom: 19
        attribution:
          'Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community'
    nat_geo_world_map:
      url: 'http://services.arcgisonline.com/ArcGIS/rest/services/NatGeo_World_Map/MapServer/tile/{z}/{y}/{x}'
      options:
        max_zoom: 12
        attribution: 'Tiles &copy; Esri &mdash; National Geographic, Esri, DeLorme, NAVTEQ, UNEP-WCMC, USGS, NASA, ESA, METI, NRCAN, GEBCO, NOAA, iPC'
    world_gray_canvas:
      url: 'http://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}'
      options:
        max_zoom: 16
        attribution: 'Tiles &copy; Esri &mdash; Esri, DeLorme, NAVTEQ'

open_weather_map:
  type: map_overlay
  options:
    attribution: 'Weather from <a href="http://openweathermap.org/" alt="World Map and worldwide Weather Forecast online">OpenWeatherMap</a>'
    opacity: 100
    maxZoom: 18
  variants:
    clouds:
      url: 'http://{s}.tile.openweathermap.org/map/clouds/{z}/{x}/{y}.png'
    clouds_classic:
      url: 'http://{s}.tile.openweathermap.org/map/clouds_cls/{z}/{x}/{y}.png'
    precipitation:
      url: 'http://{s}.tile.openweathermap.org/map/precipitation/{z}/{x}/{y}.png'
    precipitation_classic:
      url: 'http://{s}.tile.openweathermap.org/map/precipitation_cls/{z}/{x}/{y}.png'
    rain:
      url: 'http://{s}.tile.openweathermap.org/map/rain/{z}/{x}/{y}.png'
    rain_classic:
      url: 'http://{s}.tile.openweathermap.org/map/rain_cls/{z}/{x}/{y}.png'
    pressure:
      url: 'http://{s}.tile.openweathermap.org/map/pressure/{z}/{x}/{y}.png'
    pressure_contour:
      url: 'http://{s}.tile.openweathermap.org/map/pressure_cntr/{z}/{x}/{y}.png'
    wind:
      url: 'http://{s}.tile.openweathermap.org/map/wind/{z}/{x}/{y}.png'
    temperature:
      url: 'http://{s}.tile.openweathermap.org/map/temp/{z}/{x}/{y}.png'
    snow:
      url: 'http://{s}.tile.openweathermap.org/map/snow/{z}/{x}/{y}.png'

open_map_surfer:
  type: map_overlay
  options:
    attribution: 'Imagery from <a href="http://giscience.uni-hd.de/">GIScience Research Group @ University of Heidelberg</a> &mdash; Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>'
    opacity: 100
  variants:
    admin_bounds:
      url: 'http://korona.geog.uni-heidelberg.de/tiles/adminb/x={x}&y={y}&z={z}'